### PR TITLE
Add `grantComp` and `setContributorCompSpeed`

### PR DESCRIPTION
**Pull request by Pet3ris**
**WORK IN PROGRESS**

**Authors**:

- @pluriholonomic, @jmomx, @reichiang, @pet3ris
- Big thanks to Quantstamp for the broader vesting audit which covers most of this patch
- Big thanks to Compound team for help w/ review and testing

**Features**:

- This implements contributor rewards through `grantComp` and `setContributorCompSpeed`
- Added `mul_ScalarTruncate` to Exponential library
- Added `mul_ScalarTruncateAddUint` to Exponential library

**Other**

- Some CToken functions will now revert insted of returning Failures
- Bumped kovan gas limit to 6M (to allow for Comptroller deployment)
- To reduce Comptroller size: Introduced Comptroller size check `yarn checksize`
- To reduce Comptroller size: Removes several hard limits to governance controlled functions
- To reduce Comptroller size: Refactor several math/error operations to use reverts
- To reduce Comptroller size: Split `Exponential.sol` contract into `Exponential.sol` and `ExponentialNoError.sol`, Comptroller now won't include any `MathError` based operations
- To reduce Comptroller size: Removed `_setMaxAssets`

**Design decisions**

- Contributor COMP is accrued into the same `compAccrued` variable
- Contributors have to call `updateContributorRewards` with their address before claiming COMP (the reason for this is to minimize the gas impact on other non-contributor users)

**Remaining steps**

- [x] Write testnet scenario script
- [x] Conduct initial code review
- [x] Deploy and test in testnet
- [x] Deploy to mainnet
- [x] Submit proposal

### CODE REVIEW

**Review by zech564 — DISMISSED** [review]

**Comment by jflatow** [comment]
Still a very large code change but looking good. Worth noting (since its an interface change) that some functions which used to return Failures (especially e.g. in CTokens) will now revert.

**Comment by Pet3ris** [comment]
Since proposal is queued for execution, would welcome guidance on how to prepare this patch to be merged in! I've been having trouble with CI tests due to out of memory errors.

cc @jflatow

**Comment by jflatow** [comment]
We'll need to bump CI resources and/or not run some tests on CI in the future, since this is mostly running out of memory. But looks like kicking it again we got one to actually succeed. Also ran tests locally to confirm they pass, and since this has been executed as part of the protocol now (https://compound.finance/governance/proposals/30), merging to master.

**Review by jflatow — APPROVED** [review]

**Comment by Pet3ris** [comment]
Thanks so much @jflatow!

**Pull request merged**
